runmode: release                 # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 3           # pingServer函数try的次数
jwt_secret: shihuipeng
tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
 name: db_apiserver
 attr: 127.0.0.1:3306
 username: root
 password: root
db:
 name: db_apiserver
 attr: 127.0.0.1:3306
 username: root
 password: root
